//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WannaDuo {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Traducciones {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Traducciones() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WannaDuo.Traducciones", typeof(Traducciones).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Voy a jugar este tiempo: .
        /// </summary>
        public static string horas {
            get {
                return ResourceManager.GetString("horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Idioma.
        /// </summary>
        public static string idioma {
            get {
                return ResourceManager.GetString("idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Comentarios:.
        /// </summary>
        public static string notas {
            get {
                return ResourceManager.GetString("notas", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Posicion preferida.
        /// </summary>
        public static string posicion {
            get {
                return ResourceManager.GetString("posicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Quiero jugar con: .
        /// </summary>
        public static string prefe {
            get {
                return ResourceManager.GetString("prefe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Servidor.
        /// </summary>
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Nick de invocador.
        /// </summary>
        public static string soy {
            get {
                return ResourceManager.GetString("soy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Modo:.
        /// </summary>
        public static string tipo_partida {
            get {
                return ResourceManager.GetString("tipo_partida", resourceCulture);
            }
        }
    }
}
